"""
Explicit column name mappings from SimFin API to database schema
"""

# Income Statement (PL) mapping
INCOME_STATEMENT_MAPPING = {
    "Fiscal Period": "fiscal_period",
    "Fiscal Year": "fiscal_year",
    "Report Date": "report_date",
    "Publish Date": "publish_date",
    "Restated": "restated",
    "Source": "source",
    "TTM": "ttm",
    "Value Check": "value_check",
    "Data Model": "data_model",
    "Revenue": "revenue",
    "Sales & Services Revenue": "sales_services_revenue",
    "Financing Revenue": "financing_revenue",
    "Other Revenue": "other_revenue",
    "Cost of revenue": "cost_of_revenue",
    "Cost of Goods & Services": "cost_of_goods_services",
    "Cost of Financing Revenue": "cost_of_financing_revenue",
    "Cost of Other Revenue": "cost_of_other_revenue",
    "Gross Profit": "gross_profit",
    "Other Operating Income": "other_operating_income",
    "Operating Expenses": "operating_expenses",
    "Selling, General & Administrative": "selling_general_administrative",
    "Selling & Marketing": "selling_marketing",
    "General & Administrative": "general_administrative",
    "Research & Development": "research_development",
    "Depreciation & Amortization": "depreciation_amortization",
    "Provision For Doubtful Accounts": "provision_for_doubtful_accounts",
    "Other Operating Expense": "other_operating_expense",
    "Operating Income (Loss)": "operating_income_loss",
    "Non-Operating Income (Loss)": "non_operating_income_loss",
    "Interest Expense, net": "interest_expense_net",
    "Interest Expense": "interest_expense",
    "Interest Income": "interest_income",
    "Other Investment Income (Loss)": "other_investment_income_loss",
    "Foreign Exchange Gain (Loss)": "foreign_exchange_gain_loss",
    "Income (Loss) from Affiliates": "income_loss_from_affiliates",
    "Other Non-Operating Income (Loss)": "other_non_operating_income_loss",
    "Pretax Income (Loss), Adjusted": "pretax_income_loss_adjusted",
    "Abnormal Gains (Losses)": "abnormal_gains_losses",
    "Acquired In-Process R&D": "acquired_in_process_rd",
    "Merger / Acquisition Expense": "merger_acquisition_expense",
    "Abnormal Derivatives": "abnormal_derivatives",
    "Disposal of Assets": "disposal_of_assets",
    "Early extinguishment of Debt": "early_extinguishment_of_debt",
    "Asset Write-Down": "asset_write_down",
    "Impairment of Goodwill & Intangibles": "impairment_of_goodwill_intangibles",
    "Sale of Business": "sale_of_business",
    "Legal Settlement": "legal_settlement",
    "Restructuring Charges": "restructuring_charges",
    "Sale of and Unrealized Investments": "sale_of_unrealized_investments",
    "Insurance Settlement": "insurance_settlement",
    "Other Abnormal Items": "other_abnormal_items",
    "Pretax Income (Loss)": "pretax_income_loss",
    "Income Tax (Expense) Benefit, net": "income_tax_expense_benefit_net",
    "Current Income Tax": "current_income_tax",
    "Deferred Income Tax": "deferred_income_tax",
    "Tax Allowance/Credit": "tax_allowance_credit",
    "Income (Loss) from Affiliates, net of taxes": "income_loss_from_affiliates_net_of_taxes",
    "Income (Loss) from Continuing Operations": "income_loss_from_continuing_operations",
    "Net Extraordinary Gains (Losses)": "net_extraordinary_gains_losses",
    "Discontinued Operations": "discontinued_operations",
    "XO & Accounting Charges & Other": "xo_accounting_charges_other",
    "Income (Loss) Including Minority Interest": "income_loss_including_minority_interest",
    "Minority Interest": "minority_interest",
    "Net Income": "net_income",
    "Preferred Dividends": "preferred_dividends",
    "Other Adjustments": "other_adjustments",
    "Net Income Available to Common Shareholders": "net_income_available_to_common_shareholders"
}

# Balance Sheet (BS) mapping
BALANCE_SHEET_MAPPING = {
    "Fiscal Period": "fiscal_period",
    "Fiscal Year": "fiscal_year",
    "Report Date": "report_date",
    "Publish Date": "publish_date",
    "Restated": "restated",
    "Source": "source",
    "TTM": "ttm",
    "Value Check": "value_check",
    "Data Model": "data_model",
    "Cash, Cash Equivalents & Short Term Investments": "cash_cash_equivalents_short_term_investments",
    "Cash & Cash Equivalents": "cash_cash_equivalents",
    "Short Term Investments": "short_term_investments",
    "Accounts & Notes Receivable": "accounts_notes_receivable",
    "Accounts Receivable, Net": "accounts_receivable_net",
    "Notes Receivable, Net": "notes_receivable_net",
    "Unbilled Revenues": "unbilled_revenues",
    "Inventories": "inventories",
    "Raw Materials": "raw_materials",
    "Work In Process": "work_in_process",
    "Finished Goods": "finished_goods",
    "Other Inventory": "other_inventory",
    "Other Short Term Assets": "other_short_term_assets",
    "Prepaid Expenses": "prepaid_expenses",
    "Derivative & Hedging Assets (Short Term)": "derivative_hedging_assets_short_term",
    "Assets Held-for-Sale": "assets_held_for_sale",
    "Deferred Tax Assets (Short Term)": "deferred_tax_assets_short_term",
    "Income Taxes Receivable": "income_taxes_receivable",
    "Discontinued Operations (Short Term)": "discontinued_operations_short_term",
    "Miscellaneous Short Term Assets": "miscellaneous_short_term_assets",
    "Total Current Assets": "total_current_assets",
    "Property, Plant & Equipment, Net": "property_plant_equipment_net",
    "Property, Plant & Equipment": "property_plant_equipment",
    "Accumulated Depreciation": "accumulated_depreciation",
    "Long Term Investments & Receivables": "long_term_investments_receivables",
    "Long Term Investments": "long_term_investments",
    "Long Term Marketable Securities": "long_term_marketable_securities",
    "Long Term Receivables": "long_term_receivables",
    "Other Long Term Assets": "other_long_term_assets",
    "Intangible Assets": "intangible_assets",
    "Goodwill": "goodwill",
    "Other Intangible Assets": "other_intangible_assets",
    "Prepaid Expense": "prepaid_expense",
    "Deferred Tax Assets (Long Term)": "deferred_tax_assets_long_term",
    "Derivative & Hedging Assets (Long Term)": "derivative_hedging_assets_long_term",
    "Prepaid Pension Costs": "prepaid_pension_costs",
    "Discontinued Operations (Long Term)": "discontinued_operations_long_term",
    "Investments in Affiliates": "investments_in_affiliates",
    "Miscellaneous Long Term Assets": "miscellaneous_long_term_assets",
    "Total Noncurrent Assets": "total_noncurrent_assets",
    "Total Assets": "total_assets",
    "Payables & Accruals": "payables_accruals",
    "Accounts Payable": "accounts_payable",
    "Accrued Taxes": "accrued_taxes",
    "Interest & Dividends Payable": "interest_dividends_payable",
    "Other Payables & Accruals": "other_payables_accruals",
    "Short Term Debt": "short_term_debt",
    "Short Term Borrowings": "short_term_borrowings",
    "Short Term Capital Leases": "short_term_capital_leases",
    "Current Portion of Long Term Debt": "current_portion_of_long_term_debt",
    "Other Short Term Liabilities": "other_short_term_liabilities",
    "Deferred Revenue (Short Term)": "deferred_revenue_short_term",
    "Liabilities from Derivatives & Hedging (Short Term)": "liabilities_from_derivatives_hedging_short_term",
    "Deferred Tax Liabilities (Short Term)": "deferred_tax_liabilities_short_term",
    "Liabilities from Discontinued Operations (Short Term)": "liabilities_from_discontinued_operations_short_term",
    "Miscellaneous Short Term Liabilities": "miscellaneous_short_term_liabilities",
    "Total Current Liabilities": "total_current_liabilities",
    "Long Term Debt": "long_term_debt",
    "Long Term Borrowings": "long_term_borrowings",
    "Long Term Capital Leases": "long_term_capital_leases",
    "Other Long Term Liabilities": "other_long_term_liabilities",
    "Accrued Liabilities": "accrued_liabilities",
    "Pension Liabilities": "pension_liabilities",
    "Pensions": "pensions",
    "Other Post-Retirement Benefits": "other_post_retirement_benefits",
    "Deferred Compensation": "deferred_compensation",
    "Deferred Revenue (Long Term)": "deferred_revenue_long_term",
    "Deferred Tax Liabilities (Long Term)": "deferred_tax_liabilities_long_term",
    "Liabilities from Derivatives & Hedging (Long Term)": "liabilities_from_derivatives_hedging_long_term",
    "Liabilities from Discontinued Operations (Long Term)": "liabilities_from_discontinued_operations_long_term",
    "Miscellaneous Long Term Liabilities": "miscellaneous_long_term_liabilities",
    "Total Noncurrent Liabilities": "total_noncurrent_liabilities",
    "Total Liabilities": "total_liabilities",
    "Preferred Equity": "preferred_equity",
    "Share Capital & Additional Paid-In Capital": "share_capital_additional_paid_in_capital",
    "Common Stock": "common_stock",
    "Additional Paid in Capital": "additional_paid_in_capital",
    "Other Share Capital": "other_share_capital",
    "Treasury Stock": "treasury_stock",
    "Retained Earnings": "retained_earnings",
    "Other Equity": "other_equity",
    "Equity Before Minority Interest": "equity_before_minority_interest",
    "Minority Interest": "minority_interest",
    "Total Equity": "total_equity",
    "Total Liabilities & Equity": "total_liabilities_equity"
}

# Cash Flow (CF) mapping
CASH_FLOW_MAPPING = {
    "Fiscal Period": "fiscal_period",
    "Fiscal Year": "fiscal_year",
    "Report Date": "report_date",
    "Publish Date": "publish_date",
    "Restated": "restated",
    "Source": "source",
    "TTM": "ttm",
    "Value Check": "value_check",
    "Data Model": "data_model",
    "Net Income/Starting Line": "net_income_starting_line",
    "Net Income": "net_income",
    "Net Income From Discontinued Operations": "net_income_from_discontinued_operations",
    "Other Adjustments": "other_adjustments",
    "Depreciation & Amortization": "depreciation_amortization",
    "Non-Cash Items": "non_cash_items",
    "Stock-Based Compensation": "stock_based_compensation",
    "Deferred Income Taxes": "deferred_income_taxes",
    "Other Non-Cash Adjustments": "other_non_cash_adjustments",
    "Change in Working Capital": "change_in_working_capital",
    "(Increase) Decrease in Accounts Receivable": "increase_decrease_in_accounts_receivable",
    "(Increase) Decrease in Inventories": "increase_decrease_in_inventories",
    "Increase (Decrease) in Accounts Payable": "increase_decrease_in_accounts_payable",
    "Increase (Decrease) in Other": "increase_decrease_in_other",
    "Net Cash From Discontinued Operations (operating)": "net_cash_from_discontinued_operations_operating",
    "Cash from Operating Activities": "cash_from_operating_activities",
    "Change in Fixed Assets & Intangibles": "change_in_fixed_assets_intangibles",
    "Disposition of Fixed Assets & Intangibles": "disposition_of_fixed_assets_intangibles",
    "Disposition of Fixed Assets": "disposition_of_fixed_assets",
    "Disposition of Intangible Assets": "disposition_of_intangible_assets",
    "Acquisition of Fixed Assets & Intangibles": "acquisition_of_fixed_assets_intangibles",
    "Purchase of Fixed Assets": "purchase_of_fixed_assets",
    "Acquisition of Intangible Assets": "acquisition_of_intangible_assets",
    "Other Change in Fixed Assets & Intangibles": "other_change_in_fixed_assets_intangibles",
    "Net Change in Long Term Investment": "net_change_in_long_term_investment",
    "Decrease in Long Term Investment": "decrease_in_long_term_investment",
    "Increase in Long Term Investment": "increase_in_long_term_investment",
    "Net Cash From Acquisitions & Divestitures": "net_cash_from_acquisitions_divestitures",
    "Net Cash from Divestitures": "net_cash_from_divestitures",
    "Cash for Acqusition of Subsidiaries": "cash_for_acquisition_of_subsidiaries",
    "Cash for Joint Ventures": "cash_for_joint_ventures",
    "Net Cash from Other Acquisitions": "net_cash_from_other_acquisitions",
    "Other Investing Activities": "other_investing_activities",
    "Net Cash From Discontinued Operations (investing)": "net_cash_from_discontinued_operations_investing",
    "Cash from Investing Activities": "cash_from_investing_activities",
    "Dividends Paid": "dividends_paid",
    "Cash From (Repayment of) Debt": "cash_from_repayment_of_debt",
    "Cash From (Repayment of) Short Term Debt, net": "cash_from_repayment_of_short_term_debt_net",
    "Cash From (Repayment of) Long Term Debt, net": "cash_from_repayment_of_long_term_debt_net",
    "Repayments of Long Term Debt": "repayments_of_long_term_debt",
    "Cash From Long Term Debt": "cash_from_long_term_debt",
    "Cash From (Repurchase of) Equity": "cash_from_repurchase_of_equity",
    "Increase in Capital Stock": "increase_in_capital_stock",
    "Decrease in Capital Stock": "decrease_in_capital_stock",
    "Other Financing Activities": "other_financing_activities",
    "Net Cash From Discontinued Operations (financing)": "net_cash_from_discontinued_operations_financing",
    "Cash from Financing Activities": "cash_from_financing_activities",
    "Net Cash Before Disc. Operations and FX": "net_cash_before_disc_operations_and_fx",
    "Change in Cash from Disc. Operations and Other": "change_in_cash_from_disc_operations_and_other",
    "Net Cash Before FX": "net_cash_before_fx",
    "Effect of Foreign Exchange Rates": "effect_of_foreign_exchange_rates",
    "Net Changes in Cash": "net_changes_in_cash"
}

# Derived Ratios (DERIVED) mapping
DERIVED_RATIOS_MAPPING = {
    "Fiscal Period": "fiscal_period",
    "Fiscal Year": "fiscal_year",
    "Report Date": "report_date",
    "TTM": "ttm",
    "Restated": "restated",
    "Data Model": "data_model",
    "Gross Profit Margin": "gross_profit_margin",
    "Operating Margin": "operating_margin",
    "Net Profit Margin": "net_profit_margin",
    "Net Profit Margin (Adjusted)": "net_profit_margin_adjusted",
    "Return on Equity": "return_on_equity",
    "Return on Equity (Adjusted)": "return_on_equity_adjusted",
    "Return on Assets": "return_on_assets",
    "Return on Assets (Adjusted)": "return_on_assets_adjusted",
    "Return On Invested Capital": "return_on_invested_capital",
    "Return On Invested Capital (Adjusted)": "return_on_invested_capital_adjusted",
    "Cash Return On Invested Capital": "cash_return_on_invested_capital",
    "Earnings Per Share, Basic": "earnings_per_share_basic",
    "Earnings Per Share, Diluted": "earnings_per_share_diluted",
    "Sales Per Share": "sales_per_share",
    "Equity Per Share": "equity_per_share",
    "Free Cash Flow Per Share": "free_cash_flow_per_share",
    "Dividends Per Share": "dividends_per_share",
    "EBITDA": "ebitda",
    "Free Cash Flow": "free_cash_flow",
    "Free Cash Flow to Net Income": "free_cash_flow_to_net_income",
    "Free Cash Flow to Net Income (Adjusted)": "free_cash_flow_to_net_income_adjusted",
    "Dividend Payout Ratio": "dividend_payout_ratio",
    "Current Ratio": "current_ratio",
    "Debt Ratio": "debt_ratio",
    "Total Debt": "total_debt",
    "Net Debt / EBITDA": "net_debt_to_ebitda",
    "Net Debt / EBIT": "net_debt_to_ebit",
    "Liabilities to Equity Ratio": "liabilities_to_equity_ratio",
    "Piotroski F-Score": "piotroski_f_score",
    "Net Income (Adjusted)": "net_income_adjusted"
}

# Master mapping dictionary
STATEMENT_MAPPINGS = {
    "PL": INCOME_STATEMENT_MAPPING,
    "BS": BALANCE_SHEET_MAPPING,
    "CF": CASH_FLOW_MAPPING,
    "DERIVED": DERIVED_RATIOS_MAPPING
}


def map_record(record: dict, statement_type: str) -> dict:
    """
    Map API column names to database column names
    
    Args:
        record: Record from SimFin API with original column names
        statement_type: One of 'PL', 'BS', 'CF', 'DERIVED'
    
    Returns:
        Record with database column names
    """
    mapping = STATEMENT_MAPPINGS.get(statement_type, {})
    mapped_record = {}
    
    for api_col, value in record.items():
        db_col = mapping.get(api_col, api_col.lower().replace(' ', '_'))
        mapped_record[db_col] = value
    
    return mapped_record