"""
NASDAQ-100 tickers (as of 2025)
"""
#"AAPL","MSFT" removed
NASDAQ100_TICKERS = [
    "AMZN","NVDA","META","GOOG","TSLA","AVGO","COST","NFLX","AMD","CMCSA","INTC","PEP","ADBE","AMGN","CSCO","TXN","QCOM","LIN","TMUS","HON","AMAT","SBUX","INTU","ISRG","BKNG","MDLZ","ADP","PYPL","GILD","PANW","MU","ABNB","KDP","CDNS","VRTX","REGN","MAR","CHTR","LRCX","CRWD","ORLY","KLAC","SNPS","IDXX","PDD","MELI","MRVL","LULU","CPRT","EA","KHC","AZN","AEP","EXC","ADI","FTNT","FAST","DXCM","WBD","PCAR","MNST","CTAS","XEL","ODFL","CDW","PAYX","TEAM","SHOP","VRSK","CSX","ROST","TTWO","BIIB","WDAY","BKR","FANG","ZS","ON","NDAQ","TTD","DDOG","PLTR","APP","GFS","CEG","GEHC","ARM","DASH","CCEP","MSTR","ROP","AXON"
]


